name: docfx-build-and-publish

on:
  push:
    branches: [ main ]


jobs:
  # This workflow contains a single job called "build"
  generate-docs:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          name: itinero/docfx-tmpl 
          ref: refs/heads/master

      - name: Setup DocFX
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx
          
      # Runs a set of commands using the runners shell
      - name: DocFX Build
        run: docfx docfx.json
        continue-on-error: false
